### ISSUE TITLE
Hello, what's the publications and instructions for this code?

### ISSUE THREAD

**Issue by gaorunzebit** [mattjj/py4sid#2]
Hello Matthew,

I am interested about this code and want to study it. As you know, there are more than one kinds of algorithms of subspace-based system identification. Which algorithm is related to this code, it is convenient to share it? 

Thank you!
Runze

**Comment by m-nolan** [comment]
Hello Runze,

I'm not Matt, and I am not 100% certain about this, but this appears to be an implementation of the algorithms detailed in this textbook:

Van Overschee, P., & De Moor, B. (1996). Subspace Identification for Linear Systems. doi:10.1007/978-1-4613-0465-4 

A copy of the text can be accessed through sci-hub here:
[https://scihub.to/10.1007/978-1-4613-0465-4](https://scihub.to/10.1007/978-1-4613-0465-4)

**Comment by mattjj** [comment]
@m-nolan that's right! Comments like [this one](https://github.com/mattjj/py4sid/blob/5c1b5ea0a793254fe72b4b16ac6dbb0129446f72/estimation.py#L10) refer to the names of particular variants from that book.
